# server
server:
  port: 8762

logging:
    level:
        ROOT: INFO
# datasource
spring:
  datasource:
  # tomcat   
    tomcat:
      max-active: 1400
      max-idle: 1400
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: 
    schema: 
    - classpath:sql/test-schema.sql
    data: 
    - classpath:sql/banners.sql
    - classpath:sql/brand.sql
    - classpath:sql/channel.sql
    - classpath:sql/location.sql
    - classpath:sql/organization.sql
    - classpath:sql/region.sql
    - classpath:sql/store_type.sql
    - classpath:sql/store.sql
    
# exception handle
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
 
# mybatis
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
