
# server
server:
  port: 8762
  
# datasource
spring:
  datasource:
  # tomcat   
    tomcat:
      max-active: 1400
      max-idle: 1400  
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.117:3306/PGCustomer?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: pg
    password: sharepoint@admin
    
# exception handle
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
 
# mybatis
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
